spring:
  application:
    name: TrackingApiApplication

  datasource:
    url: jdbc:h2:mem:trackingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
